[package]
name = "AoC"
version = "0.1.0"
authors = ["Marcelo Lazaroni <lazaronijunior@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
